# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nexus.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'nexus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnexus.proto\x12\x05nexus\"0\n\rRouterRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"m\n\x0eRouterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0eselected_route\x18\x02 \x01(\t\x12\x18\n\x10\x63omplexity_score\x18\x03 \x01(\x02\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x02\"/\n\x0cSwarmRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"e\n\rSwarmResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0b\x61gent_trace\x18\x02 \x03(\t\x12\x14\n\x0c\x66inal_output\x18\x03 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x04 \x01(\x02\x32I\n\rRouterService\x12\x38\n\tRouteTask\x12\x14.nexus.RouterRequest\x1a\x15.nexus.RouterResponse2M\n\x0cSwarmService\x12=\n\x10\x45xecuteSwarmTask\x12\x13.nexus.SwarmRequest\x1a\x14.nexus.SwarmResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTERREQUEST']._serialized_start=22
  _globals['_ROUTERREQUEST']._serialized_end=70
  _globals['_ROUTERRESPONSE']._serialized_start=72
  _globals['_ROUTERRESPONSE']._serialized_end=181
  _globals['_SWARMREQUEST']._serialized_start=183
  _globals['_SWARMREQUEST']._serialized_end=230
  _globals['_SWARMRESPONSE']._serialized_start=232
  _globals['_SWARMRESPONSE']._serialized_end=333
  _globals['_ROUTERSERVICE']._serialized_start=335
  _globals['_ROUTERSERVICE']._serialized_end=408
  _globals['_SWARMSERVICE']._serialized_start=410
  _globals['_SWARMSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
