# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nexus_pb2 as nexus__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteTask = channel.unary_unary(
                '/nexus.RouterService/RouteTask',
                request_serializer=nexus__pb2.RouterRequest.SerializeToString,
                response_deserializer=nexus__pb2.RouterResponse.FromString,
                _registered_method=True)


class RouterServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RouteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteTask,
                    request_deserializer=nexus__pb2.RouterRequest.FromString,
                    response_serializer=nexus__pb2.RouterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.RouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.RouterService/RouteTask',
            nexus__pb2.RouterRequest.SerializeToString,
            nexus__pb2.RouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SwarmServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteSwarmTask = channel.unary_unary(
                '/nexus.SwarmService/ExecuteSwarmTask',
                request_serializer=nexus__pb2.SwarmRequest.SerializeToString,
                response_deserializer=nexus__pb2.SwarmResponse.FromString,
                _registered_method=True)


class SwarmServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteSwarmTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwarmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteSwarmTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSwarmTask,
                    request_deserializer=nexus__pb2.SwarmRequest.FromString,
                    response_serializer=nexus__pb2.SwarmResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.SwarmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.SwarmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwarmService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteSwarmTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.SwarmService/ExecuteSwarmTask',
            nexus__pb2.SwarmRequest.SerializeToString,
            nexus__pb2.SwarmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
